name: Compile Arctica CI

on:
  push:
    branches: [ "main", "actionstest" ]
  pull_request:
    branches: [ "main", "actionstest" ]

  workflow_dispatch:

jobs:
  build-arctica:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 12.22.9, 14.x, 14.6.0]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      #- name: Install frontend dependencies
      #  run: npm install arctica-frontend/
      - name: Compile the frontend submodule
        run: cd arctica-frontend/ && npm ci && npm run build --if-present && cd ../
      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install backend dependencies
        run: sudo apt install -y libgtk-3-dev
      - name: Compile the backend
        uses: actions-rs/cargo@v1
        with:
          command: build
